<a href="https://colab.research.google.com/github/bioduds/ALGEBRA-COMPUTACIONAL-UFMG/blob/main/Lista_3_ALC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lista de Exercícios 3: Álgebra Linear Computacional"
---

<font color="green">**Prazo de submissão:</font>** 23:55 do dia 01/02/2021

**Aluno:** Eduardo Capanema (2020041515)

**Professores:** Erickson e Fabricio

In [2]:
## Alguns inits e loads - descomente e rode se não visualizar corretamente

# ! sudo apt-get install texlive-latex-recommended 
# ! sudo apt install texlive-latex-extra
# ! sudo apt install dvipng

import numpy as np

# Problema 1
---

Quais das matrizes $S_1, S_2, S_3, S_4$ tem dois autovalores positivos? Use um teste, não calcule os $\lambda's$. Encontre também um vetor $x$ tal que $x^TS_1x<0$, então $S_1$ não é uma matriz definida positiva.

$$
S_1 = 
\begin{bmatrix}
5 & 6 \\ 
6 & 7 \\ 
\end{bmatrix}
$$ 

$$
S_2 = 
\begin{bmatrix}
-1 & -2 \\ 
-2 & -5 \\ 
\end{bmatrix}
$$

$$
S_3 = 
\begin{bmatrix}
1 & 10 \\ 
10 & 100 \\ 
\end{bmatrix}
$$

$$
S_4 = 
\begin{bmatrix}
1 & 10 \\ 
10 & 101 \\ 
\end{bmatrix}
$$


In [ ]:
# Vamos criar as matrizes
S1 = np.array( [ [5, 6], [6, 7] ] )
S2 = np.array( [ [-1, -2], [-2, -5] ] )
S3 = np.array( [ [1, 10], [10, 100] ] )
S4 = np.array( [ [1, 10], [10, 101] ] )


### <font color="green">**Resposta:**</font>

A partir de: 

**Testes para A p.d.:** Os seguintes testes são condições necessárias e suficientes equivalentes para que uma matriz $A = A^T$
seja positiva definida

1. $x^TAx > 0, ∀x \neq 0$ equivalente a $x^TS_1x<0$, para $S_1$
2. <font color="blue"> Todos os autovalores de $A$ são positivos.</font>
3. Todas as matrizes líderes possuem determinantes positivos.
4. Todos os pivôs são positivos (e não é preciso, teoricamente, fazer trocas de linhas na eliminação gaussiana em A).
5. $∃R$ com colunas L.I. tal que $A = R^TR$

Fonte: http://www.nacad.ufrj.br/~amit/alglin/aula8 

e como não devemos calcular os autovalores para avaliar e as 5 condições são suficientes equivalentes, basta testarmos uma delas. Utilizando o site matrixcalc.org encontramos as seguintes matrizes com os pivôs:

1. para S1: $\left(\begin{matrix}
1 & \frac{6}{5} & 0 \\
0 & \frac{-1}{5} & 0
\end{matrix}\right)$

2. para S2: $\left(\begin{matrix}
1 & 1 & 0 \\
0 & -3 & 0
\end{matrix}\right)$

3. para S3: $\left(\begin{matrix}
1 & 10 & 0 \\
0 & 0 & 0
\end{matrix}\right)$

4. para S4: $\left(\begin{matrix}
1 & 10 & 0 \\
0 & 1 & 0
\end{matrix}\right)$

Concluímos, portanto que as matrizes $S_3$ e $S_4$ são definidas positivas e, portanto, seus autovalores são positivos.

Finalmente, poderemos, portanto, somente encontrar valores de $x$ para $S_1$ e $S_2$. Faremos o cálculo em python:


In [ ]:
nD1 = np.array( [ [-1.1], [1] ] ) # após muita luta
rS1 = nD1.T @ S1 @ nD1
print( "Valor negativo para x^TS1x:", rS1 ) 

nD2 = np.array( [ [-1.1], [1] ] ) # o mesmo valor tb funciona para S2
rS2 = nD2.T @ S2 @ nD2
print( "Valor negativo para x^TS2x:", rS2 ) 

Valor negativo para x^TS1x: [[-0.15]]
Valor negativo para x^TS2x: [[-1.81]]


# <font color="blue">Problema 2</font>
---

Mostre que $ \|v\|_2 \leq \sqrt{n} \|v\|_{\infty} $ sempre. Prove também que $ \|v\|_1 \leq \sqrt{n} \|v\|_2 $, escolhendo um vetor $w$ adequado e aplicando a desigualdade de Cauchy-Schwarz.

**Para a primeira proposição,** podemos elevar ambos os lados ao quadrado obtendo:

$( \| v \|_2 )^2 \leq ( \sqrt{ n } \| v \|_{\infty} )^2$

A norma-2, euclidiana, é dada por: $ \sqrt{ v_1^2 + ... +v_n^2 } $ que, ao elevarmos ao quadrado, fica: $v_1^2 + ... +v_n^2$

Agora, elevaremos o lado direito da nossa inequação ao quadrado, obtendo: $n ( \| v \|_{\infty} )^2$

Sabemos que $ \| v \|_{\infty} = \max_{i \in \{1,...,n\} } |v_i|$ e, portanto, o lado direito fica: $n ( |v_i| )^2$.

Fica fácil perceber que o maior valor possível para $ v_1^2 + ... +v_n^2 $ será para o máximo e, portanto, podemos afirmar que 

$n |v_n|^2 $ será sempre menor ou igual a $n ( |v_n| )^2$ como queríamos demonstrar.

**Para a segunda proposição,** podemos aplicar raciocínio semelhante, elevando os dois lados ao quadrado:

Ficamos com $ ( \| v \|_1 )^2 = ( \sqrt{ n }  \| v \|_2 )^2 \implies ( \| v \|_1 )^2 = n ( \| v \|_2 )^2 $

Assim, teremos: $ (|v_1|)^2 + ... + (|v_n|)^2 = n ( \| v \|_2 )^2 $ como queríamos demonstrar

---
Destacamos abaixo a base do que utilizamos no exercício para fins de aprendizado:

As normas canônicas definidas nestes espaços são as chamadas normas ${\displaystyle \ell ^{p}}\ell ^{p}$:

${\displaystyle \|x\|_{p}={\Big (}\sum _{i=1}^{n}|x_{i}|^{p}{\Big )}^{\frac {1}{p}}~~,1\leqslant p<\infty }$

${\displaystyle \|x\|_{\infty }=\max _{i\in \{1,\ldots ,n\}}|x_{i}|}{\displaystyle \|x\|_{\infty }=\max _{i\in \{1,\ldots ,n\}}|x_{i}|}$

O caso particular em que ${\displaystyle p=2}$ corresponde à norma euclidiana:

${\displaystyle \|x\|_{2}={\Big (}\sum _{i=1}^{n}|x_{i}|^{2}{\Big )}^{\frac {1}{2}}}$

Para a norma infinita:

${\displaystyle \left\|\mathbf {x} \right\|_{\infty }:=\max _{i}\left|x_{i}\right|}$





# <font color="blue">Problema 3</font>
---

Considere o uso do SVD truncado de posto k para compressão de imagens em escala de cinza (0 a 255) de tamanho 1024 x 768.

(a) No caso de uma única imagem decomposta usando SVD, quantos bytes precisam ser armazenados para reconstruir a imagem? Qual o valor máximo de k para o qual a compressão vale a pena?

(b) Agora suponha que queiramos usar um único SVD para comprimir várias imagens. Para isso, iremos representar as imagens como vetores de tamanho 786432 (= 1024×768). Quantos bytes serão necessários para
armazenar 10 imagens? E quanto a 1000 imagens?

### <font color="green">**Resposta letra a:**</font>

Para reconstruir, precisamos somente da ordem da matriz sigma em bytes. No caso, 768 bytes. Em torno de 80-90% da "energia", que nos daria algo em torno de $ 0.85 \times 768 = 652 $

### <font color="green">**Resposta letra b:**</font>

Precisaremos somente de 768 bytes para a matriz sigma e 10 bytes adicionais, um para cada k das 10 imagens ou 1000 bytes adicionais no caso de 1000 imagens.



# <font color="blue">Problema 4</font>
---

Seja Q uma matriz ortogonal. Mostre que: 

(a) os valores singulares de $Q$ são todos iguais a $1$, e que

(b) $Q = UΣV^T$ com $U = Q$, $Σ = I$ e $V >= I$ é um SVD válido.

Matriz Ortogonal: Inversa = Transposta

### <font color="green">**Resposta letra a:**</font>

Sendo assim, os valores singulares de $Q$ que encontramos na decomposição SVD, precisam ser iguais a 1, ou seja, a matriz sigma deve ser a matriz identidade, pois se $ Q =  UΣV^T $ e para $Q$ ser ortogonal, teremos $ Q = VV^T\Sigma $, onde $ VV^T = I $. Repare que isso obrigará a matriz $ \Sigma $ a ser igual à identidade.

### <font color="green">**Resposta letra b:**</font>

Neste caso, se $ \Sigma $ corresponde à matriz identidade, se fizermos $ U = Q $, teremos uma possibilidade para o SVD ser válido: $ V = I $, ou seja $ Q = QII = Q $ que é trivial.

# <font color="blue">Problema 5</font>
---

Sem fazer contas (i.e., sem fazer multiplicação de matrizes ou calcular polinômios característicos), encontre os σ's, u's e v's da matriz

$$
A = 
\begin{bmatrix}
0 & 2 & 0 \\ 
0 & 0 & 3 \\ 
0 & 0 & 0 \\ 
\end{bmatrix} = UΣV^T
$$ 

Dica: as matrizes ortogonais U e V são matrizes de permutação

### <font color="green">**Resposta:**</font>

A matriz de permutação de $1's$ e $0's$ permite que façamos a escolha (matrizes com $1's$ em colunas em que o restante dos valores é $0$ permitem que colunas sejam selecionadas na matriz original, no caso, A). Assim, basta que selecionemos para cada coluna o valor não nulo e o ordenemos do maior para o menor, ficando com $ \sigma = [ 3, 2, 0] $, fazendo nossa U ser o marcador da posição dos termos:

$$
U = 
\begin{bmatrix}
0 & 1 & 0 \\ 
1 & 0 & 0 \\ 
0 & 0 & 1 \\ 
\end{bmatrix}
$$

E V transposta deverá ser a ordenação desses valores (lidos de baixo para cima):

$$
V^T = 
\begin{bmatrix}
0 & 0 & 1 \\ 
0 & 1 & 0 \\ 
1 & 0 & 0 \\ 
\end{bmatrix}
$$



In [7]:
# Verificando nosso raciocínio (não considerar como resposta pois o exercício pede para não calcular)

A = np.array( [ [0, 2, 0], [0, 0, 3], [0, 0, 0] ] )
U, sigma, Vt = np.linalg.svd( A )
print( U )
print( sigma )
print( Vt )

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
[3. 2. 0.]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
