<a href="https://colab.research.google.com/github/bioduds/ALGEBRA-COMPUTACIONAL-UFMG/blob/main/Prova_1_ALC_Eduardo_Capanema_2020041515.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Prova 1 - Eduardo Capanema (2020041515)

In [1]:
import numpy as np

# Questão 2

$C = \begin{bmatrix}  0.00 & -0.94 & -0.33\\  0.11 & -0.33 & 0.94\\  -0.99 & -0.04 & 0.10\\\end{bmatrix} \begin{bmatrix}  11.60 & 0.00 & 0.00\\  0.00 & 4.90 & 0.00\\  0.00 & 0.00 & 0.06\\\end{bmatrix}\begin{bmatrix}  0.33 & -0.51 & 0.79\\  0.75 & -0.37 & -0.55\\  -0.58 & -0.77 & -0.26\\\end{bmatrix} $


In [65]:
U = np.array( [ [0, -0.94, -0.33], [0.11, -0.33, 0.94], [-0.99, -0.04, 0.10] ] )
sigma = np.array( [ [ 11.6, 0, 0 ], [0, 4.9, 0], [0, 0, 0.06] ] )
Vt = np.array( [ [ 0.33, -0.51, 0.79 ], [0.75, -0.37, -0.55], [-0.58, -0.77, -0.26] ] )
sigma2 = np.array( [ [ 11.6, 0, 0 ], [0, 4.9, 0], [0, 0, 0.0] ] )


C = U @ sigma @ Vt.T
C

U1 = np.array( [[1],[1],[1]] )
N1 = np.linalg.norm( ( C @ U1 ) )
print( N1 )

C2 = U @ sigma2 @ Vt.T
print( C2 )



9.901996523535038
[[ 2.34906  1.70422  3.54662]
 [ 1.24575  1.55529  0.50501]
 [-3.68976 -8.54048  6.81164]]


# Questão 3

Como c representa as colunas linearmente independentes, e a terceira coluna é C.L (primeira menos a segunda), nosso R resultará da simples reconstrução das colunas (vide Decomposição Coluna/Linha, i.e. CR)



# Questão 4

$A = \begin{bmatrix} 7 & 2 & -7 \\ 6 & 9 & 3 \\ 1 & -7 & -9 \end{bmatrix}$

[1, 0], [0, 1], [1,1], [-1, 1]




In [46]:
A = np.array( [ [7, 2, -7], [6, 9, 3], [1, -7, -9] ] )
U = np.array( [1, 1, 1] ) # encontrei por tentativa e erro 

Ninf = np.linalg.norm( A, np.inf )
print( Ninf )

NU = np.linalg.norm( ( A @ U ), np.inf )
NU


18.0


18.0

# Questão 6

Vamos obter a matriz transposta $ A^T = B $ e dividir os elementos pela norma

In [34]:
A = np.array( [ [ -1.51, 0.93, -1.15 ], [ -1.29, -1.49, 1.15 ], [ -0.22, 2.43, 1.15 ] ] )
B = A.T
n1 = np.linalg.norm( B[0] )
n2 = np.linalg.norm( B[1] )
n3 = np.linalg.norm( B[2] )
print( n1, n2, n3 )

a11 = -1.51/n1; a12 = 0.93/n2; a13 = -1.15/n3; 
a21 = -1.29/n1; a22 = -1.49/n2; a23 = 1.15/n3; 
a31 = -0.22/n1; a32 = 2.43/n2; a33 = 1.15/n3; 

print( a11, a12, a13 )
print( a21, a22, a23 )
print( a31, a32, a33 )


1.9981491435826306 2.998316194132967 1.9918584287042087
-0.7556993454916024 0.3101740909847339 -0.5773502691896257
-0.645597454095475 -0.4969455866314554 0.5773502691896257
-0.11010189139612751 0.8104548828955951 0.5773502691896257


# Questão 7

Utilizaremos este conhecimento (que obtivemos na lista 3 de exercícios ao fazê-la):

**Testes para A p.d.:** Os seguintes testes são condições necessárias e suficientes equivalentes para que uma matriz $A = A^T$
seja positiva definida

1. $x^TAx > 0, ∀x \neq 0$ equivalente a $x^TS_1x<0$, para $S_1$
2. <font color="blue"> Todos os autovalores de $A$ são positivos.</font>
3. Todas as matrizes líderes possuem determinantes positivos.
4. Todos os pivôs são positivos (e não é preciso, teoricamente, fazer trocas de linhas na eliminação gaussiana em A).
5. $∃R$ com colunas L.I. tal que $A = R^TR$

Fonte: http://www.nacad.ufrj.br/~amit/alglin/aula8 

7.1. 

7.2. Todos os pivôs são positivos (e não é preciso, teoricamente, fazer trocas de linhas na eliminação gaussiana em A). 




In [60]:
C = np.array( [ [1, 0, 0], [1, 1, 1] ] )
C.T

E = C @ C.T
print( np.linalg.eigvals( E ) )

F = C.T @ C
print( np.linalg.eigvals( F ) )


[0.58578644 3.41421356]
[ 3.41421356e+00  5.85786438e-01 -1.80567699e-33]
